### ISSUE TITLE
Don't work on Ubuntu 18.04 (AWS)

### ISSUE THREAD

**Issue by gstrainovic** [javanile/vtiger-demo#4]
![image](https://user-images.githubusercontent.com/8936333/65822264-5054d800-e241-11e9-8cd3-530d97582d2b.png)

**Comment by francescobianco** [comment]
Try to disable error reporting using environment variable

```yaml
environment:
  - VT_DEBUG=0
```

**Comment by gstrainovic** [comment]
also tried with 
```
environment:
  - VT_DEBUG=true

```
instead of
```

environment:
  - VT_DEBUG=0

```
![image](https://user-images.githubusercontent.com/8936333/65823378-3f15c680-e255-11e9-9880-19ef97e00cb9.png)

**Comment by francescobianco** [comment]
Place 
VT_SITEURL=https://mydomain.com

read this
https://github.com/javanile/vtiger-demo/issues/3

**Comment by gstrainovic** [comment]
Thanks for your help. I couldn't test it anymore, but I assume it was because of it.
